/* DEPARTAMENT ALTER */
ALTER TABLE DEPARTAMENT ADD CONSTRAINT UQ_DEPTO_CODE UNIQUE (CODE);

/* ACCESS LEVEL ALTER */
/* codigo como level access ej. (G1, G2, G3) */

/* SHIFT */
ALTER TABLE SHIFT ADD COLUMN DAY_COUNT INT DEFAULT 0 NOT NULL; -- TURNOS QUE ABARCAN MAS DE UN DIA
ALTER TABLE SHIFT ADD COLUMN STATUS VARCHAR(20) NOT NULL DEFAULT 'ENABLED';
ALTER TABLE SHIFT ADD COLUMN CREATED_BY VARCHAR(50);
ALTER TABLE SHIFT ADD COLUMN CREATED_ON DATETIME DEFAULT NOW();
ALTER TABLE SHIFT ADD COLUMN UPDATED_ON DATETIME;
ALTER TABLE SHIFT ADD COLUMN UPDATED_BY VARCHAR(40);

/* CHECADAS Y TARJETA */ 
ALTER TABLE CARD ADD COLUMN EMPLOYEE_ID INT;
ALTER TABLE CARD ADD CONSTRAINT UQ_NUMBER UNIQUE (NUMBER);
ALTER TABLE CARD ADD CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);

DROP TABLE IF EXISTS CARD_CHECK;
CREATE TABLE CARD_CHECK (
	CARD_CHECK_ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID INT NOT NULL,
    TIME_EXP VARCHAR(6) NOT NULL,
    CHECK_DT DATETIME NOT NULL,
    TYPE VARCHAR(5) NOT NULL DEFAULT 'IN', -- CHECADA DE ENTRADA Y SALIDA
    CARD_ID INT NOT NULL,
	STATUS VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
    CREATED_BY VARCHAR(50),
	CREATED_ON DATETIME DEFAULT NOW(),
	UPDATED_ON DATETIME,
	UPDATED_BY VARCHAR(40),
	CONSTRAINT PK_CARD_CHECK PRIMARY KEY (CARD_CHECK_ID ASC)
);

ALTER TABLE CARD_CHECK ADD CONSTRAINT CH_TYPE CHECK (TYPE IN ('IN', 'OUT')) ;
ALTER TABLE CARD_CHECK ADD CONSTRAINT FK_CARD_ID FOREIGN KEY (CARD_ID) REFERENCES CARD(CARD_ID);
ALTER TABLE CARD_CHECK ADD CONSTRAINT FK_CHECK_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID);

/* JOB ADDITON */
DROP TABLE IF EXISTS JOB;
CREATE TABLE JOB (
	JOB_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
    CREATED_BY VARCHAR(50),
	CREATED_ON DATETIME DEFAULT NOW(),
	UPDATED_ON DATETIME,
	UPDATED_BY VARCHAR(40),
	CONSTRAINT PK_JOB PRIMARY KEY (JOB_ID ASC)
);

/* EDITING POSITION */

ALTER TABLE POSITION ADD JOB_ID INT NOT NULL;
ALTER TABLE POSITION ADD CONSTRAINT FK_JOB_POSITION FOREIGN KEY (JOB_ID) REFERENCES JOB(JOB_ID);
ALTER TABLE POSITION ADD CONSTRAINT UQ_JOB_POSITION UNIQUE (POSITION_ID, DEPARTAMENT_ID, JOB_ID); -- THIS MAY BE NOT OPTIMAL

/* EDITING EMPLOYEE_ACCESS_LEVEL */
ALTER TABLE EMPLOYEE_ACCESS_LEVEL ADD COLUMN CREATED_BY VARCHAR(50);
ALTER TABLE EMPLOYEE_ACCESS_LEVEL ADD COLUMN CREATED_ON DATETIME DEFAULT NOW();
ALTER TABLE EMPLOYEE_ACCESS_LEVEL ADD COLUMN UPDATED_ON DATETIME;
ALTER TABLE EMPLOYEE_ACCESS_LEVEL ADD COLUMN UPDATED_BY VARCHAR(40);

/* INSERTS */
INSERT INTO ACCESS_LEVEL (NAME) VALUES ('G1'), ('G2'), ('G3');
INSERT INTO SHIFT (NAME, CLOCK_IN, CLOCK_OUT, DAY_COUNT, LUNCH_TIME) VALUES 
	('MATUTINE', maketime(8, 00, 00), maketime(18, 00, 00), 0, maketime(12, 00, 00)), 
	('VESPERTINE', maketime(16, 00, 00), maketime(2, 00, 00), 1, maketime(20, 00, 00));
