/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 21-jun.-2022 07:00:24 p. m. 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Access_Level` CASCADE
;

DROP TABLE IF EXISTS `Card` CASCADE
;

DROP TABLE IF EXISTS `Department` CASCADE
;

DROP TABLE IF EXISTS `Employee` CASCADE
;

DROP TABLE IF EXISTS `Employee_Access_Level` CASCADE
;

DROP TABLE IF EXISTS `Position` CASCADE
;

DROP TABLE IF EXISTS `Shifts` CASCADE
;

/* Create Tables */

CREATE TABLE `Access_Level`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`status` VARCHAR(20) NOT NULL,
	`created_on` DATETIME NOT NULL,
	`created_by` VARCHAR(40) NOT NULL,
	`updated_on` DATETIME NOT NULL,
	`updated_by` VARCHAR(40) NOT NULL,
	CONSTRAINT `PK_Access_Level` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Card`
(
	`id` INT NOT NULL,
	`number` VARCHAR(20) NOT NULL,
	`created_by` VARCHAR(50) NULL,
	`created_on` DATETIME NOT NULL,
	`updated_on` DATETIME NOT NULL,
	`updated_by` VARCHAR(40) NOT NULL,
	CONSTRAINT `PK_Card` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Department`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`code` VARCHAR(20) NOT NULL,
	`created_on` DATETIME NOT NULL,
	`created_by` VARCHAR(40) NOT NULL,
	`updated_on` DATETIME NOT NULL,
	`updated_by` VARCHAR(40) NOT NULL,
	CONSTRAINT `PK_Department` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Employee`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(50) NOT NULL,
	`last_name` VARCHAR(50) NULL,
	`status` VARCHAR(20) NOT NULL,
	`created_on` DATETIME NOT NULL,
	`created_by` VARCHAR(40) NOT NULL,
	`updated_on` DATETIME NOT NULL,
	`updated_by` INT NOT NULL,
	`card_id` INT NOT NULL,
	`position_id` INT NOT NULL,
	`shift` INT NOT NULL,
	CONSTRAINT `PK_Employee` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Employee_Access_Level`
(
	`employee_id` INT NOT NULL,
	`access_level_id` INT NOT NULL,
	CONSTRAINT `PK_Employee_Access_Level` PRIMARY KEY (`employee_id` ASC, `access_level_id` ASC)
)

;

CREATE TABLE `Position`
(
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`status` VARCHAR(50) NULL,
	`created_on` DATETIME NOT NULL,
	`created_by` VARCHAR(40) NOT NULL,
	`updated_on` DATETIME NOT NULL,
	`department_id` INT NOT NULL,
	`updated_by` VARCHAR(40) NOT NULL,
	CONSTRAINT `PK_Position` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `Shifts`
(
	`id` INT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`clock_in` TIME NOT NULL,
	`clock_out` TIME NOT NULL,
	`lunch_time` TIME NOT NULL,
	CONSTRAINT `PK_Shifts` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `Employee` 
 ADD INDEX `IXFK_Employee_Card` (`card_id` ASC)
;

ALTER TABLE `Employee` 
 ADD INDEX `IXFK_Employee_Position` (`position_id` ASC)
;

ALTER TABLE `Employee` 
 ADD INDEX `IXFK_Employee_Shifts` (`shift` ASC)
;

ALTER TABLE `Employee_Access_Level` 
 ADD INDEX `IXFK_Employee_Access_Level_Access_Level` (`access_level_id` ASC)
;

ALTER TABLE `Employee_Access_Level` 
 ADD INDEX `IXFK_Employee_Access_Level_Employee` (`employee_id` ASC)
;

ALTER TABLE `Position` 
 ADD INDEX `IXFK_Position_Department` (`department_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `Employee` 
 ADD CONSTRAINT `FK_Employee_Position`
	FOREIGN KEY (`position_id`) REFERENCES `Position` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Employee` 
 ADD CONSTRAINT `FK_Employee_Shifts`
	FOREIGN KEY (`shift`) REFERENCES `Shifts` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Employee_Access_Level` 
 ADD CONSTRAINT `FK_Employee_Access_Level_Access_Level`
	FOREIGN KEY (`access_level_id`) REFERENCES `Access_Level` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Employee_Access_Level` 
 ADD CONSTRAINT `FK_Employee_Access_Level_Employee`
	FOREIGN KEY (`employee_id`) REFERENCES `Employee` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Position` 
 ADD CONSTRAINT `FK_Position_Department`
	FOREIGN KEY (`department_id`) REFERENCES `Department` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1 
;
